### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by Demimos** [Demimos/Vedma_backend#4]
Authification

**Comment by Joaolfelicio** [comment]
Hello @Demimos, what type of authentication are you looking for? JWT and Identity Core?

If so, please assign it to me, thanks!

**Comment by Demimos** [comment]
> 
> 
> Hello @Demimos, what type of authentication are you looking for? JWT and Identity Core?
> 
> If so, please assign it to me, thanks!

ok

**Comment by Joaolfelicio** [comment]
Need some more information:

Should you be authenticated to call **all** endpoints?
How should the user authenticate, email + password or username + password?
Any special configuration that you would like for the JWT? (exemple: Expire date, Security Algorithm)

**Comment by Demimos** [comment]
> Need some more information:
> 
> Should you be authenticated to call **all** endpoints?
> How should the user authenticate, email + password or username + password?
> Any special configuration that you would like for the JWT? (exemple: Expire date, Security Algorithm)

1. Not at all. U can make test endpoint to check.
2.  Email+pass
3. Tokenm should be valid for 1 day. Aes

**Comment by Joaolfelicio** [comment]
Working on it right now!

**Comment by Joaolfelicio** [comment]
[Reading Suggestion](https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/common-web-application-architectures#traditional-n-layer-architecture-applications)

Take a look into that, it can improve your application architecture by a lot!

**Comment by Joaolfelicio** [comment]
Sent you a pull request, take a look into the code and maybe try to implement a more decoupled architecture.
If you have any doubt, let me know and I will gladly help you and explain it to you.

Thanks.

**Comment by Joaolfelicio** [comment]
Btw, do you mind adding the label: "hacktoberfest" to the repository or "hacktoberfest-accepted" to my PR? Thanks.
